version: "3.3"

services:
  backend:
    build: ./backend
    container_name: hackademytodo-backend
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    container_name: hackademytodo-frontend
    environment:
      - NEXT_PUBLIC_API_HOST=localhost
      - NEXT_PUBLIC_API_PROTOCOL=http
      - NEXT_PUBLIC_API_PORT=8080
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: npm run dev

    
